version: "3.9"
services:
  mysql_server:
    container_name: mysql_server_test
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=todo_database
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306